##### profiles: local
spring:
  application:
    name: partner

  main:
    allow-bean-definition-overriding: true

  jackson:
    time-zone: Asia/Seoul

  servlet:
    encoding:
      force-response: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oynee_db
    username: oynee
    password: oynee1234
    hikari:
      auto-commit: false
      maximum-pool-size: 2
      pool-name: springPostgresqlHikariCP
      connection-timeout: 3500
      leak-detection-threshold: 60000
      data-source-properties:
        rewriteBatchedStatements: true

  jpa:
    database: postgresql
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: false
        highlight_sql: true
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        default_schema: partner
        jdbc:
          batch_size: 250
        query:
          plan_cache_max_size: 256
          plan_parameter_metadata_max_size: 16
          in_clause_parameter_padding: true

server:
  port: 9090

decorator:
  datasource:
    p6spy:
      enable-logging: true
